### ISSUE TITLE
Steam Launcher doesn't work with python3

### ISSUE THREAD

**Issue by wberrier** [teeedubb/teeedubb-xbmc-repo#20]
I may have to gather more detailed information later... bug background is that Fedora32 (rpmfusion) is shipping kodi with python3 support.  I'm getting errors when loading the steam launcher:

```
2020-05-07 19:35:18.275 T:140641544079104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'TabError'>
                                            Error Contents: inconsistent use of tabs and spaces in indentation (main.py, line 159)
                                            Traceback (most recent call last):
                                              File "/home/wberrier/.kodi/addons/script.steam.launcher/default.py", line 2, in <module>
                                                import resources.main
                                              File "/home/wberrier/.kodi/addons/script.steam.launcher/resources/main.py", line 159
                                                display = None
                                                             ^
                                            TabError: inconsistent use of tabs and spaces in indentation
                                            -->End of Python script error report<--
```

**Comment by wberrier** [comment]
Issue referenced here: https://rpmfusion.org/CommonBugs

**Comment by teeedubb** [comment]
The add-on has not been updated to work with Kodi python 3 builds as of yet, though I have started and should have it ready before the official Kodi 19 release.

**Comment by wberrier** [comment]
Sorry for the false alarm on this one.

I was under the impression that python3 was supported for Kodi 18.x.  I didn't realize python3 wouldn't be required until 19.x.

**Comment by teeedubb** [comment]
Beta of a Kodi 19/Python 3 build is in the forum thread.
