### ISSUE TITLE
Steam Launcher fails on Kodi Matrix Beta 2

### ISSUE THREAD

**Issue by Kidlike** [teeedubb/teeedubb-xbmc-repo#23]
_Thanks for this great plugin, I've been using it for years with Kodi Leia :)_

I downloaded and installed the patched version of this addon from here: https://forum.kodi.tv/showthread.php?tid=157499&pid=2956167#pid2956167

From what I understand from that forum thread, this should work for Kodi Matrix... But it's not, at least for me.

**Script logs:**
```
2020-12-27 15:34:16.855 T:165086   DEBUG <general>: script.steam.launcher: ****Running Steam-Launcher v3.5.0....
2020-12-27 15:34:16.855 T:165086   DEBUG <general>: script.steam.launcher: running on osAndroid, osOsx, osLinux, osWin: False False True False 
2020-12-27 15:34:16.855 T:165086   DEBUG <general>: script.steam.launcher: System text encoding in use: utf-8
2020-12-27 15:34:16.855 T:165086 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2020-12-27 15:34:16.856 T:165086   DEBUG <general>: script.steam.launcher: usr scripts are set to be checked for updates...
2020-12-27 15:34:16.856 T:165086   DEBUG <general>: script.steam.launcher: usr scripts are not set to be deleted, running version check
2020-12-27 15:34:16.856 T:165086   DEBUG <general>: script.steam.launcher: sys "steam.launcher.script.revision=": 017
2020-12-27 15:34:16.856 T:165086   DEBUG <general>: script.steam.launcher: usr "steam.launcher.script.revision=": 017
2020-12-27 15:34:16.856 T:165086   DEBUG <general>: script.steam.launcher: userdata script are up to date
2020-12-27 15:34:16.856 T:165086   DEBUG <general>: script.steam.launcher: skipping deleting userdata scripts, option disabled: delUserScriptSett = false
2020-12-27 15:34:16.856 T:165086   DEBUG <general>: script.steam.launcher: script file already exists, skipping copy to userdata: /home/kidlike/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launcher.sh
2020-12-27 15:34:16.868 T:165086   DEBUG <general>: script.steam.launcher: wmctrl present, checking if a window manager is running...
2020-12-27 15:34:16.882 T:165086   DEBUG <general>: script.steam.launcher: A window manager is running...
2020-12-27 15:34:16.893 T:165086   DEBUG <general>: script.steam.launcher: xdotool present...
2020-12-27 15:34:16.894 T:165086   DEBUG <general>: script.steam.launcher: running program file check, option is enabled: filePathCheck = true
2020-12-27 15:34:16.894 T:165086   DEBUG <general>: script.steam.launcher: Steam executable exists /usr/bin/steam
2020-12-27 15:34:16.894 T:165086   DEBUG <general>: script.steam.launcher: Xbmc executable exists /usr/bin/kodi
2020-12-27 15:34:16.896 T:165086   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: a bytes-like object is required, not 'str'
                                                   Traceback (most recent call last):
                                                     File "/home/kidlike/.kodi/addons/script.steam.launcher/default.py", line 2, in <module>
                                                       import resources.main
                                                     File "/home/kidlike/.kodi/addons/script.steam.launcher/resources/main.py", line 389, in <module>
                                                       makeScriptExec()
                                                     File "/home/kidlike/.kodi/addons/script.steam.launcher/resources/main.py", line 110, in makeScriptExec
                                                       if '\r\n' in open(scriptPath,'rb').read():
                                                   TypeError: a bytes-like object is required, not 'str'
                                                   -->End of Python script error report<--
```

**Versions:**
```
$ kodi --version
19.0-BETA2 (18.9.821) Git:20201207-nogitfound Media Center Kodi

$ dnf info kodi
Installed Packages
Name         : kodi
Version      : 19.0
Release      : 0.8.20201207git8cc9e80.fc33
Architecture : x86_64
Size         : 71 M
Source       : kodi-19.0-0.8.20201207git8cc9e80.fc33.src.rpm
Repository   : @System
From repo    : rpmfusion-free-updates
Summary      : Media center
URL          : http://www.kodi.tv/
License      : GPLv2+ and GPLv3+ and LGPLv2+ and BSD and MIT
Description  : Kodi is a free cross-platform media-player jukebox and entertainment hub.
             : Kodi can play a spectrum of of multimedia formats, and featuring playlist,
             : audio visualizations, slideshow, and weather forecast functions, together
             : third-party plugins.

$ inxi -S
System:    Kernel: 5.9.15-200.fc33.x86_64 x86_64 bits: 64 Desktop: KDE Plasma 5.20.4 
           Distro: Fedora release 33 (Thirty Three) 
```

**Comment by hedmo** [comment]
@Kidlike have you tried to patch it with https://github.com/hedmo/hedmos-overlay/blob/master/media-plugins/kodi-steam-launcher/files/startup_error.patch

**Comment by teeedubb** [comment]
Thanks again @hedmo, your fix is much appreciated!
Updated addon has been pushed to the repo so your system should update automatically.
