### ISSUE TITLE
Error: module 'xbmc' has no attribute 'translatePath'

### ISSUE THREAD

**Issue by smorar** [teeedubb/teeedubb-xbmc-repo#24]
Currently running Kodi: 20.0-ALPHA1 (19.90.101) Git:20210403-145e4133eb
I get the following exception thrown when attempting to use this plugin:
```
2021-04-05 01:58:13.343 T:1238310   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/home/tv/.kodi/addons/script.steam.launcher/default.py", line 2, in <module>
                                                       import resources.main
                                                     File "/home/tv/.kodi/addons/script.steam.launcher/resources/main.py", line 384, in <module>
                                                       scripts_path = os.path.join(getAddonDataPath(), 'scripts')
                                                     File "/home/tv/.kodi/addons/script.steam.launcher/resources/main.py", line 59, in getAddonDataPath
                                                       path = xbmc.translatePath('special://profile/addon_data/%s' % scriptid)
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
```

**Comment by smorar** [comment]
xbmc.translatePath has been depreciated in Kodi's Python API v19, and moved to xbmcvfs.translatePath:
https://codedocs.xyz/AlwinEsch/kodi/python_v19.html

**Comment by graysky2** [comment]
@smorar - I tried replacing `tempdir = xbmc.translatePath('special://temp/')` with `tempdir = xbmcvfs.translatePath('special://temp/'` on the latest build from the Nexus branch but an still getting errors in the script.  Am I not calling it correctly?

Full script:
```
#!/usr/bin/env python3

import xbmc
import os

#tempdir = xbmc.translatePath('special://temp/')
tempdir = xbmcvfs.translatePath('special://temp/')
tempfile0 = os.path.join(tempdir, 'audiooutput0')

print("CURRENT AUDIO DEVICE:")
print((xbmc.executeJSONRPC('{"jsonrpc":"2.0","method":"Settings.GetSettingValue", "params":{"setting":"audiooutput.audiodevice"},"id":1}')))
if not os.path.isfile(tempfile0):
  # optical out
  xbmc.executeJSONRPC('{"jsonrpc":"2.0", "method":"Settings.SetSettingValue", "params":{"setting":"audiooutput.audiodevice", "value":"ALSA:iec958:CARD=PCH,DEV=0"}, "id":1}')
  xbmc.executeJSONRPC('{"jsonrpc":"2.0", "method":"GUI.ShowNotification", "params":{"title":"AUDIO OUTPUT", "message":"Soundbar", "image":"/var/lib/kodi/fiber.png"}, "id":1}')
  file = open(tempfile0, "a")
  file.close()
else:
  # HDMI out
  xbmc.executeJSONRPC('{"jsonrpc":"2.0", "method":"Settings.SetSettingValue", "params":{"setting":"audiooutput.audiodevice", "value":"ALSA:hdmi:CARD=HDMI,DEV=3"}, "id":1}')
  xbmc.executeJSONRPC('{"jsonrpc":"2.0", "method":"GUI.ShowNotification", "params":{"title":"AUDIO OUTPUT", "message":"TV Speakers", "image":"/var/lib/kodi/hdtv-green.png"}, "id":1}')
  os.remove(tempfile0)
```

**Comment by graysky2** [comment]
Ah, I see now that a new import statement is needed:
```
import xbmcvfs
```

**Comment by teeedubb** [comment]
This has been fixed in the latest release.
Let me know if theres any issues
