### ISSUE TITLE
Error when using steam launcher on NixOS: `which` not found

### ISSUE THREAD

**Issue by Soupstraw** [teeedubb/teeedubb-xbmc-repo#35]
I tried running the steam launcher on NixOS with Kodi 20.1 and got this error in the logs:
```
2023-05-28 16:17:39.202 T:1714    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: [Errno 2] No such file or directory: 'which'
                                                   Traceback (most recent call last):
                                                     File "/home/telku/.kodi/addons/script.steam.launcher/default.py", line 2, in <module>
                                                       import resources.main
                                                     File "/home/telku/.kodi/addons/script.steam.launcher/resources/main.py", line 393, in <module>
                                                       fileChecker()
                                                     File "/home/telku/.kodi/addons/script.steam.launcher/resources/main.py", line 173, in fileChecker
                                                       if subprocess.call(["which", "xdotool"]) != 0:
                                                     File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/subprocess.py", line 345, in call
                                                       with Popen(*popenargs, **kwargs) as p:
                                                     File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/subprocess.py", line 971, in __init__
                                                       self._execute_child(args, executable, preexec_fn, close_fds,
                                                     File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/subprocess.py", line 1863, in _execute_child
                                                       raise child_exception_type(errno_num, err_msg, err_filename)
                                                   FileNotFoundError: [Errno 2] No such file or directory: 'which'
                                                   -->End of Python script error report<--
```

I also tried to disable the checks for `xdotool` in the configuration, but I still get the same error.

**Comment by teeedubb** [comment]
The program which isn't installed, have you tried installing it via the system package manager?

**Comment by Soupstraw** [comment]
I think the issue is with how it's packaged in Nix, it doesn't have `which` as a dependency.

**Comment by teeedubb** [comment]
I have no exposure or experience with NixOS, but you'll need to to install which yourself or edit the addon to not use it.
